shortener/users/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""users/views.py: User views."""

from flask import render_template, Blueprint, request, flash, redirect,\
    url_for
from flask.ext.login import login_user, login_required, logout_user,\
    current_user
from shortener import app, db, bcrypt, random_str, is_email
from shortener.models import User, Invitation, ResetPassword
from shortener.emailer.emailer import Emailer
from datetime import datetime, timedelta

users_blueprint = Blueprint(
    'users', __name__,
    template_folder='templates'
)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Login route."""
    if request.method == "POST":
        user = User.query.filter_by(email=request.form['email']).first()
        if user is not None and bcrypt.check_password_hash(
            user.password, request.form['password']
        ):
            login_user(user)
            return redirect(url_for('links.add'))

        else:
            flash('Invalid username or password.')

    return render_template('login.html')


@users_blueprint.route('/logout')
@login_required
def logout():
    """Logout route."""
    logout_user()
    flash('You were logged out')
    return redirect(url_for('users.login'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """Register route."""
    if request.method == "POST":
        if(
            not request.form.get('email') or
            not request.form.get('password') or
            not request.form.get('invite')
        ):
            flash('Please ensure you fill in all fields.')
            return render_template('register.html')
        else:
            invite = Invitation.query.filter_by(
                email=request.form['email']
            ).first()
            if invite and invite.code == request.form.get('invite'):
                db.session.add(
                    User(request.form['email'], request.form['password'])
                )
                db.session.commit()
                flash('Thanks for signing up! Please login below.')
                return redirect(url_for('users.login'))
            else:
                flash('Sorry, we don\'t have a invite that matches that email '
                      'address and invitation code.')

    return render_template('register.html')


@users_blueprint.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """Forgot password route."""
    if request.method == "POST":
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if not user:
            flash('Sorry, we don\'t have that email address in our system.')
            return render_template('forgot_password.html')
        else:
            code = random_str(25)
            expires = datetime.utcnow() + timedelta(hours=24)
            db.session.add(ResetPassword(user, code, expires))
            db.session.commit()
            reset_url = '{}users/reset_password/{}'.format(
                app.config['DOMAIN_NAME'],
                code
            )
            # send email
            message = """\
            <html>
                <head></head>
                <body>
                    <p>Hello,</p>
                    <p>Someone has requested an email reset.</p>
                    <p>If that was you, please go to <a href="{}">{}</a>.</p>
                    <p>If it was not you, please just ignore this email.</p>
                    <p>Please note that replies to this email are unlikely to
                    be read in a timely fashion if at all.</p>
                </body>
            </html>
            """.format(reset_url, reset_url)
            email = Emailer(user.email, app.config.get('ADMIN_EMAIL'),
                            'Email reset', message)
            email.send()
            flash('Your password has been reset, please check your email.')

    return render_template('forgot_password.html')


@users_blueprint.route('/reset_password/<path:path>', methods=['GET', 'POST'])
def reset_password(path):
    """Reset password route."""
    if request.method == "POST":
        password = request.form.get('password')
        user = request.form.get('user_id')
        if password and user:
            user = User.query.get(user)
            user.password = bcrypt.generate_password_hash(password)
            db.session.commit()
            flash('Your password has been updated. Please login below.')
            return redirect(url_for('users.login'))
        else:
            flash('Sorry, something\'s not right here. Did you enter and '
                  'email address?.')

    reset = ResetPassword.query.filter_by(code=path).first_or_404()
    # moke sure link not expired
    if reset.expires < datetime.utcnow():
        flash('That link has expired. Please reset your password again.')
        return redirect(url_for('users.forgot_password'))
    return render_template('reset_password.html', user=reset.user_id)


@users_blueprint.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    """Edit user route."""
    if request.method == "POST":
        email = request.form.get('email')
        if not email or not is_email(email):
            flash('Please enter a valid email address.')
            return render_template('edit.html', user=current_user)
        user = User.query.filter_by(email=email).first()
        # if email is already taken
        if user and user.id != current_user.id:
            flash('That email address is already in use.')
        else:
            user = User.query.get(current_user.id)
            # update password if changed
            if request.form['password'] != '':
                user.password = bcrypt.generate_password_hash(
                    request.form['password']
                )
            # update email if changed
            if current_user.email != request.form['email']:
                user.email = request.form['email']
            db.session.commit()
            flash('Your details have been updated')
    return render_template('edit.html', user=current_user)


@users_blueprint.route('/invitation', methods=['GET', 'POST'])
@login_required
def invitation():
    """Invitation route."""
    if request.method == "POST":
        email = request.form.get('email')
        if not is_email(email):
            flash('That email doesn\'t look like an email address...')
            return render_template('invitation.html')
        if not email:
            flash('Aren\'t you forgetting something?')
            return render_template('invitation.html')
        invite = Invitation.query.filter_by(email=email).first()
        current_user = User.query.filter_by(email=email).first()
        if invite or current_user:
            flash('{} has already been sent an invitation.'.format(email))
            return render_template('invitation.html')
        code = random_str()
        db.session.add(Invitation(email, code))
        db.session.commit()
        invite_url = '{}users/register'.format(
            app.config.get('DOMAIN_NAME'))
        flash('{} has been sent an invitation.'.format(email))

        # send email
        message = """\
        <html>
            <head></head>
            <body>
                <p>Hello,</p>
                <p>Someone has been kind enough to send you an
                invitation to {}.</p>
                <p>To activate your account go to:
                <a href="{}">{}</a>. and end the code '{}'</p>
                <p>Please note that replies to this email are unlikely
                to be read in a timely fashion if at all.</p>
            </body>
        </html>
        """.format(app.config.get('DOMAIN_NAME'),
                   invite_url, invite_url, code)
        email = Emailer(
            email,
            app.config.get('ADMIN_EMAIL'),
            '{} invitation'.format(app.config.get('DOMAIN_NAME')),
            message
        )
        email.send()
    return render_template('invitation.html')

shortener/users/templates/edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit your details:</h1>
{% for message in get_flashed_messages() %}
    <p class="has-error">{{ message }}</p>
{% endfor %}
<form id="login-form" method="post" action="{{ url_for('users.edit') }}">
    <div class="form-group">
        <label for="email">Email:</label>
        <input class="form-control" id="email" name="email" value="{{ user.email }}" type="text" placeholder="Your Email Address" />
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input class="form-control" id="password" name="password" type="password" placeholder="Password" />
    </div>
    <button type="submit" class="form-control btn btn-warning">Submit</button>
</form>
{% endblock %}

shortener/users/templates/forgot_password.html
{% extends "base.html" %}

{% block content %}
<h1>Forgot Password?</h1>
{% for message in get_flashed_messages() %}
    <p class="has-error">{{ message }}</p>
{% endfor %}
<p>Please enter your email below and we'll reset your password:</p>
<form id="login-form" method="post" action="{{ url_for('users.forgot_password') }}">
    <div class="form-group">
        <label for="email">Email:</label>
        <input class="form-control" name="email" id="email" type="text" placeholder="Your Email Address" />
    </div>
    <button type="submit" class="form-control btn btn-warning">Submit</button>
</form>
{% endblock %}

shortener/users/templates/invitation.html
{% extends "base.html" %}

{% block content %}
<h1>Invite someone to join</h1>
{% for message in get_flashed_messages() %}
    <p class="has-error">{{ message }}</p>
{% endfor %}
<form id="invitation-form" method="post" action="{{ url_for('users.invitation') }}">
    <div class="form-group">
        <label for="email">Enter the email address of the person you would like to invite:</label>
        <input class="form-control" id="email" name="email" type="text" placeholder="hello@example.com" />
    </div>
    <button class="form-control btn btn-warning" type="submit">Submit</button>
</form>
{% endblock %}

shortener/users/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
{% for message in get_flashed_messages() %}
	<p class="has-error">{{ message }}</p>
{% endfor %}
<form id="login-form" method="post" action="{{ url_for('users.login') }}">
	<div class="form-group">
		<label for="email">Email:</label>
		<input class="form-control" id="email" name="email" type="text" placeholder="Your Email Address" />
	</div>
	<div class="form-group">
		<label for="password">Password:</label>
		<input class="form-control" id="password" name="password" type="password" placeholder="Password" />
	</div>
	<button class="form-control btn btn-warning" type="submit">Submit</button>
</form>
<p><a href="{{ url_for('users.forgot_password') }}">Forgot password?</a></p>
<p>This site is an <strong>invitation only</strong> link shortening service. For an invitation please email <a href="mailto:{{ config.get('ADMIN_EMAIL') }}">{{ config.get('CONTACT_EMAIL') }}</a></p>
{% endblock %}

shortener/users/templates/register.html
{% extends "base.html" %}

{% block content %}
<h1>Register</h1>
{% for message in get_flashed_messages() %}
	<p class="has-error">{{ message }}</p>
{% endfor %}
<form id="login-form" method="post" action="{{ url_for('users.register') }}">
    <div class="form-group">
        <label for="email">Email:</label>
        <input class="form-control" id="email" name="email" type="text" placeholder="Your Email Address" />
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input class="form-control" id="password" name="password" type="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <label for="invite">Invitation code:</label>
        <input class="form-control" id="invite" name="invite" type="text" placeholder="Invitation code" />
    </div>
    <div class="form-group">
    <button type="submit" class="form-control btn btn-warning">Submit</button>
</form>
{% endblock %}

shortener/users/templates/reset_password.html
{% extends "base.html" %}

{% block content %}
<h1>Enter your new password:</h1>
{% for message in get_flashed_messages() %}
    <p class="has-error">{{ message }}</p>
{% endfor %}
<form id="reset-form" method="post" action="/users/reset_password">
    <div class="form-group">
        <label for="password">New password:</label>
        <input class="form-control" id="password" name="password" type="password" placeholder="New Password" />
    </div>
    <input type="hidden" name="user_id" value="{{ user }}" />
    <button type="submit" class="form-control btn btn-warning">Submit</button>
</form>
{% endblock %}